[build]
  publish = "."
  functions = "netlify/functions"
   [functions.anthropic]
    timeout = 30 # Increase timeout to 30 seconds
[[redirects]]
  from = "/chat/*"
  to = "/chat/index.html"
  status = 200